const monday = window.mondaySdk();
const COLUMN_TITLES = { DATE: "Date:", TRUCK_QTY: "Truck QTY", DIRECTION: "IN/OUT", OPS: "BOL/OPS:", EQUIPMENT: "Equipment:", STATUS: "Order Status" };
const today = new Date(); today.setHours(0,0,0,0);
function parseDate(valText){ if(!valText) return null; const parts = String(valText).split(" to "), start=new Date(parts[0]); start.setHours(0,0,0,0); const end=parts[1]?new Date(parts[1]):new Date(parts[0]); end.setHours(23,59,59,999); return {start,end}; }
function inRange(d,range){ const startOfWeek=new Date(today); startOfWeek.setDate(today.getDate()-today.getDay()); startOfWeek.setHours(0,0,0,0); const endOfWeek=new Date(startOfWeek); endOfWeek.setDate(startOfWeek.getDate()+6); endOfWeek.setHours(23,59,59,999); if(range==="today") return d.start<=today&&d.end>=today; if(range==="week") return d.start<=endOfWeek&&d.end>=startOfWeek; return true; }
function matchesDir(dir,desired){ if(desired==="BOTH") return true; return (dir||"").toUpperCase()===desired; }
const {data:ctx}=await monday.get("context"); const BOARD_ID=ctx?.boardId;
const gql=`query{ boards(ids:${BOARD_ID}){ items{ id name column_values{ title text } } } }`;
const res=await monday.api(gql); const items=res?.data?.boards?.[0]?.items||[];
const records=items.map(it=>{ const cols=it.column_values||[]; function find(t){return cols.find(c=>(c.title||"").trim().toLowerCase()===t.trim().toLowerCase());} const dateCol=find(COLUMN_TITLES.DATE), qtyCol=find(COLUMN_TITLES.TRUCK_QTY), dirCol=find(COLUMN_TITLES.DIRECTION), opsCol=find(COLUMN_TITLES.OPS), eqpCol=find(COLUMN_TITLES.EQUIPMENT), statCol=find(COLUMN_TITLES.STATUS); return {id:it.id,name:it.name,dateRange:parseDate(dateCol?.text),qty:Number(qtyCol?.text||0),direction:(dirCol?.text||"").toUpperCase(),ops:opsCol?.text||it.name,equipment:eqpCol?.text||"",status:statCol?.text||""}; });
let state={range:"today",dir:"BOTH"};
function applyFilters(){return records.filter(r=>r.dateRange&&inRange(r.dateRange,state.range)&&matchesDir(r.direction,state.dir));}
function computeSummary(filtered){const inCount=filtered.filter(r=>r.direction==="IN").reduce((s,r)=>s+(r.qty||0),0);const outCount=filtered.filter(r=>r.direction==="OUT").reduce((s,r)=>s+(r.qty||0),0);return{inCount,outCount,total:inCount+outCount};}
function renderSummary(){const todayRecs=records.filter(r=>r.dateRange&&inRange(r.dateRange,"today"));const weekRecs=records.filter(r=>r.dateRange&&inRange(r.dateRange,"week"));const t=computeSummary(todayRecs),w=computeSummary(weekRecs);document.getElementById("summaryBar").innerHTML=`<div class="box"><div class="title">Today</div><div class="value">${t.total} Trucks</div></div><div class="box"><div class="title">Week</div><div class="value">${w.total} Trucks</div></div>`;}
function renderCalendar(){const filtered=applyFilters();const grid=document.getElementById("calendarGrid");const days=[];const now=new Date(today);if(state.range==="today")days.push(now);else if(state.range==="week"){const start=new Date(now);start.setDate(now.getDate()-now.getDay());for(let i=0;i<7;i++){days.push(new Date(start.getFullYear(),start.getMonth(),start.getDate()+i));}}else{const first=new Date(now.getFullYear(),now.getMonth(),1);const last=new Date(now.getFullYear(),now.getMonth()+1,0);for(let d=new Date(first);d<=last;d.setDate(d.getDate()+1))days.push(new Date(d));}const byDay={};for(const d of days){const key=d.toISOString().slice(0,10);byDay[key]={in:0,out:0};}for(const r of filtered){const s=new Date(r.dateRange.start),e=new Date(r.dateRange.end);for(let d=new Date(s);d<=e;d.setDate(d.getDate()+1)){const k=d.toISOString().slice(0,10);if(byDay[k]){if(r.direction==="IN")byDay[k].in+=r.qty;if(r.direction==="OUT")byDay[k].out+=r.qty;}}}grid.innerHTML=days.map(d=>{const key=d.toISOString().slice(0,10);const bucket=byDay[key]||{in:0,out:0};return`<div class="day"><div class="date">${d.toLocaleDateString(undefined,{month:"short",day:"numeric"})}</div><div class="chips"><span class="chip in">IN:${bucket.in}</span><span class="chip out">OUT:${bucket.out}</span></div></div>`;}).join("");}
function render(){renderSummary();renderCalendar();}
document.querySelectorAll('button[data-range]').forEach(b=>b.addEventListener('click',()=>{state.range=b.getAttribute('data-range');render();}));document.querySelectorAll('button[data-dir]').forEach(b=>b.addEventListener('click',()=>{state.dir=b.getAttribute('data-dir');render();}));render();